import type { ActivityItem, DashboardProject, DealTask, ProjectStatus, TaskPriority, TaskStatus } from "@/types";

export const statusLabels: Record<ProjectStatus, string> = {
  NEW: "New",
  SCREENING: "Screening",
  MEETING_SCHEDULED: "Meeting scheduled",
  DUE_DILIGENCE: "Due diligence",
  IC_PREPARATION: "IC preparation",
  IC_APPROVED: "IC approved",
  LEGAL: "Legal",
  INVESTED: "Invested",
  PASSED: "Passed",
  ON_HOLD: "On hold",
};

export const statusOrder: ProjectStatus[] = [
  "NEW",
  "SCREENING",
  "MEETING_SCHEDULED",
  "DUE_DILIGENCE",
  "IC_PREPARATION",
  "IC_APPROVED",
  "LEGAL",
  "INVESTED",
  "PASSED",
  "ON_HOLD",
];

export const taskStatusLabels: Record<TaskStatus, string> = {
  TODO: "To do",
  IN_PROGRESS: "In progress",
  DONE: "Done",
  BLOCKED: "Blocked",
};

export const taskPriorityLabels: Record<TaskPriority, string> = {
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  URGENT: "Urgent",
};

export const projects: DashboardProject[] = [
  {
    id: "helio",
    slug: "helio",
    name: "HelioGrid Series A",
    company: "HelioGrid",
    sector: "Climate",
    subsector: "Energy infrastructure",
    geography: "Singapore",
    status: "DUE_DILIGENCE",
    owner: "Alice Chen",
    source: "Founder referral",
    summary: "Distributed energy orchestration platform for commercial buildings.",
    thesis: "Software layer for behind-the-meter energy assets as grid flexibility revenue pools expand.",
    risk: "Pilot concentration with three REIT customers and still-evolving tariff regulation.",
    expectedCheck: 2200000,
    amount: 18000000,
    valuation: 92000000,
    priority: 2,
    nextStep: "Commercial reference calls",
    lastTouch: "Today",
    probability: 68,
    progress: 52,
    documents: 14,
    contacts: [
      {
        id: "c1",
        name: "Evan Koh",
        title: "Co-founder & CEO",
        organization: "HelioGrid",
        relationship: "Founder",
        email: "evan@heliogrid.example",
      },
      {
        id: "c2",
        name: "Mia Lau",
        title: "Managing Director",
        organization: "Harbor FA",
        relationship: "Deal source",
        email: "mia@harborfa.example",
      },
    ],
    tasks: [
      {
        id: "t1",
        title: "Review data room index",
        description: "Confirm missing commercial and finance materials.",
        status: "TODO",
        priority: "HIGH",
        owner: "Ben Wang",
        dueDate: "May 29",
        projectId: "helio",
      },
      {
        id: "t2",
        title: "Complete REIT customer calls",
        description: "Validate deployment cycle, savings attribution, and expansion budget.",
        status: "IN_PROGRESS",
        priority: "URGENT",
        owner: "Alice Chen",
        dueDate: "May 30",
        projectId: "helio",
      },
    ],
    meetings: [
      {
        id: "m1",
        title: "Technical diligence call",
        date: "Jun 3, 09:30",
        participants: ["CTO", "Alice Chen", "Advisor"],
        outcome: "Open",
      },
    ],
    metrics: [
      { label: "ARR", value: "$2.4M", trend: "+38% QoQ" },
      { label: "Gross margin", value: "71%", trend: "+6 pts" },
      { label: "Pilot sites", value: "42", trend: "+11" },
    ],
  },
  {
    id: "nova",
    slug: "nova",
    name: "NovaLedger Seed",
    company: "NovaLedger",
    sector: "Fintech",
    subsector: "CFO automation",
    geography: "Hong Kong",
    status: "SCREENING",
    owner: "Ben Wang",
    source: "FA inbound",
    summary: "Finance workflow automation for multi-entity accounting teams.",
    thesis: "Regional CFO teams need clean workflow systems before layering on heavier analytics.",
    risk: "Revenue quality is early and channel dependency may dilute go-to-market learning.",
    expectedCheck: 750000,
    amount: 6000000,
    valuation: 28000000,
    priority: 3,
    nextStep: "Clarify retention cohort",
    lastTouch: "Yesterday",
    probability: 34,
    progress: 18,
    documents: 6,
    contacts: [
      {
        id: "c3",
        name: "Rachel Ng",
        title: "Founder",
        organization: "NovaLedger",
        relationship: "Founder",
        email: "rachel@novaledger.example",
      },
    ],
    tasks: [
      {
        id: "t3",
        title: "Build cohort question list",
        description: "Ask for logo churn, entity count expansion, and implementation time by cohort.",
        status: "TODO",
        priority: "MEDIUM",
        owner: "Ben Wang",
        dueDate: "Jun 1",
        projectId: "nova",
      },
    ],
    meetings: [
      {
        id: "m2",
        title: "Initial founder screen",
        date: "Jun 2, 14:00",
        participants: ["Rachel Ng", "Ben Wang"],
        outcome: "Scheduled",
      },
    ],
    metrics: [
      { label: "ARR", value: "$620K", trend: "+22% QoQ" },
      { label: "Customers", value: "31", trend: "+8" },
      { label: "Payback", value: "9 mo", trend: "Early" },
    ],
  },
  {
    id: "atlas",
    slug: "atlas",
    name: "AtlasBio Series B",
    company: "AtlasBio",
    sector: "Healthcare",
    subsector: "Diagnostics",
    geography: "Shanghai",
    status: "IC_PREPARATION",
    owner: "Alice Chen",
    source: "Co-investor",
    summary: "Point-of-care diagnostics platform for chronic disease monitoring.",
    thesis: "Consumables-led recurring revenue with strong hospital distribution leverage.",
    risk: "Regulatory timing and reimbursement coverage vary by province.",
    expectedCheck: 4200000,
    amount: 35000000,
    valuation: 180000000,
    priority: 1,
    nextStep: "Draft IC memo",
    lastTouch: "Today",
    probability: 74,
    progress: 71,
    documents: 23,
    contacts: [
      {
        id: "c4",
        name: "Dr. Lina Zhou",
        title: "CEO",
        organization: "AtlasBio",
        relationship: "Founder",
        email: "lina@atlasbio.example",
      },
      {
        id: "c5",
        name: "Marcus Li",
        title: "Partner",
        organization: "BluePeak Ventures",
        relationship: "Co-investor",
        email: "marcus@bluepeak.example",
      },
    ],
    tasks: [
      {
        id: "t4",
        title: "Finalize IC memo",
        description: "Add reimbursement sensitivity and updated cap table notes.",
        status: "IN_PROGRESS",
        priority: "URGENT",
        owner: "Alice Chen",
        dueDate: "May 31",
        projectId: "atlas",
      },
      {
        id: "t5",
        title: "Legal structure check",
        description: "Confirm offshore structure and preferred share economics.",
        status: "TODO",
        priority: "HIGH",
        owner: "Ben Wang",
        dueDate: "Jun 4",
        projectId: "atlas",
      },
    ],
    meetings: [
      {
        id: "m3",
        title: "IC pre-read",
        date: "Jun 5, 16:00",
        participants: ["Investment Committee", "Alice Chen"],
        outcome: "Drafting",
      },
    ],
    metrics: [
      { label: "Revenue", value: "$18.7M", trend: "+64% YoY" },
      { label: "GM", value: "58%", trend: "+4 pts" },
      { label: "Hospitals", value: "218", trend: "+39" },
    ],
  },
  {
    id: "foundry",
    slug: "foundry",
    name: "FoundryOps Series A",
    company: "FoundryOps",
    sector: "Industrial",
    subsector: "Manufacturing software",
    geography: "Shenzhen",
    status: "MEETING_SCHEDULED",
    owner: "Ben Wang",
    source: "Conference",
    summary: "Workflow system for precision manufacturing quote-to-cash.",
    thesis: "Vertical SaaS opportunity in fragmented advanced manufacturing suppliers.",
    risk: "Buyer urgency can vary with factory utilization and export cycles.",
    expectedCheck: 1600000,
    amount: 14000000,
    valuation: 76000000,
    priority: 2,
    nextStep: "Founder call",
    lastTouch: "Yesterday",
    probability: 46,
    progress: 28,
    documents: 5,
    contacts: [
      {
        id: "c6",
        name: "Tao Lin",
        title: "CEO",
        organization: "FoundryOps",
        relationship: "Founder",
        email: "tao@foundryops.example",
      },
    ],
    tasks: [
      {
        id: "t6",
        title: "Prepare founder call agenda",
        description: "Focus on ICP, implementation timeline, and expansion motion.",
        status: "DONE",
        priority: "MEDIUM",
        owner: "Ben Wang",
        dueDate: "May 27",
        projectId: "foundry",
      },
    ],
    meetings: [
      {
        id: "m4",
        title: "Founder call",
        date: "Jun 3, 11:00",
        participants: ["Tao Lin", "Ben Wang"],
        outcome: "Scheduled",
      },
    ],
    metrics: [
      { label: "ARR", value: "$1.8M", trend: "+31% QoQ" },
      { label: "NRR", value: "126%", trend: "+9 pts" },
      { label: "Factories", value: "57", trend: "+12" },
    ],
  },
  {
    id: "meridian",
    slug: "meridian",
    name: "Meridian Foods Growth",
    company: "Meridian Foods",
    sector: "Consumer",
    subsector: "Food supply chain",
    geography: "Jakarta",
    status: "NEW",
    owner: "Alice Chen",
    source: "Banker intro",
    summary: "B2B cold-chain marketplace for hotels and restaurant groups.",
    thesis: "Procurement fragmentation and freshness SLAs create room for workflow-led consolidation.",
    risk: "Working capital intensity and spoilage control need deeper diligence.",
    expectedCheck: 3000000,
    amount: 28000000,
    valuation: 135000000,
    priority: 2,
    nextStep: "Assign screening owner",
    lastTouch: "2 days ago",
    probability: 22,
    progress: 8,
    documents: 3,
    contacts: [
      {
        id: "c7",
        name: "Adi Putra",
        title: "CFO",
        organization: "Meridian Foods",
        relationship: "Management",
        email: "adi@meridianfoods.example",
      },
    ],
    tasks: [
      {
        id: "t7",
        title: "Create first-pass memo",
        description: "Summarize market, unit economics, and key diligence gaps.",
        status: "TODO",
        priority: "LOW",
        owner: "Alice Chen",
        dueDate: "Jun 6",
        projectId: "meridian",
      },
    ],
    meetings: [],
    metrics: [
      { label: "GMV", value: "$42M", trend: "+48% YoY" },
      { label: "Take rate", value: "8.5%", trend: "+1.2 pts" },
      { label: "Cities", value: "6", trend: "+2" },
    ],
  },
  {
    id: "cipher",
    slug: "cipher",
    name: "CipherWorks Seed",
    company: "CipherWorks",
    sector: "Security",
    subsector: "Application security",
    geography: "Seoul",
    status: "ON_HOLD",
    owner: "Ben Wang",
    source: "Outbound",
    summary: "Developer-first application security posture management.",
    thesis: "Security teams are shifting remediation ownership toward engineering workflows.",
    risk: "Crowded market and unclear wedge against established platforms.",
    expectedCheck: 900000,
    amount: 8000000,
    valuation: 36000000,
    priority: 3,
    nextStep: "Wait for Q2 usage data",
    lastTouch: "Last week",
    probability: 18,
    progress: 16,
    documents: 4,
    contacts: [
      {
        id: "c8",
        name: "Jisoo Park",
        title: "Founder",
        organization: "CipherWorks",
        relationship: "Founder",
        email: "jisoo@cipherworks.example",
      },
    ],
    tasks: [
      {
        id: "t8",
        title: "Review Q2 usage once shared",
        description: "Assess active developer growth and enterprise conversion.",
        status: "BLOCKED",
        priority: "MEDIUM",
        owner: "Ben Wang",
        dueDate: "Jun 12",
        projectId: "cipher",
      },
    ],
    meetings: [],
    metrics: [
      { label: "ARR", value: "$410K", trend: "+12% QoQ" },
      { label: "Users", value: "2.8K", trend: "+18%" },
      { label: "Pipeline", value: "$1.2M", trend: "Unverified" },
    ],
  },
];

export const tasks: DealTask[] = projects.flatMap((project) => project.tasks);

export const activities: ActivityItem[] = [
  {
    id: "a1",
    action: "Project updated",
    detail: "AtlasBio moved into IC preparation after reference calls.",
    actor: "Alice Chen",
    time: "Today 09:42",
  },
  {
    id: "a2",
    action: "Document added",
    detail: "HelioGrid uploaded a revised data room index.",
    actor: "Ben Wang",
    time: "Yesterday 17:18",
  },
  {
    id: "a3",
    action: "Meeting scheduled",
    detail: "FoundryOps founder call set for next Wednesday.",
    actor: "Ben Wang",
    time: "Yesterday 11:05",
  },
  {
    id: "a4",
    action: "New opportunity",
    detail: "Meridian Foods added from banker intro.",
    actor: "Alice Chen",
    time: "2 days ago",
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug);
}
